plugins:
  - jekyll-seo-tag

title: Unrealm SMP | Practical Information
description: Unrealm SMP is a Minecraft server running the Create mod and a customised world generation system!
logo: /assets/logo.png
url: https://www.unrealm.net/